#!/usr/bin/env sh

if [ -n "$1" ]; then
  files="$(fd --type file --extension "$1" .)"
else
  files="$(fd --type file  .)"
fi

result="$(printf "$files" | fzf)"

test -n "$result" && xdg-open "$result" || printf '%s\n' "No file selected."
