#!/usr/bin/env bash
# Downlaod the thumbnail of a YT video and open it with the default image viewer.

vidId=$(yt-dlp --print id "$1")
fileName="/tmp/thumbnail-$vidId"

yt-dlp --write-thumbnail --convert-thumbnails jpg --skip-download -o "$fileName" "$1"

xdg-open "$fileName.jpg"
